# Generated by Django 5.1.4 on 2025-01-06 16:41

from django.db import migrations, models

import undine.persisted_queries.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PersistedQuery",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            undine.persisted_queries.validators.validate_name,
                        ],
                    ),
                ),
                (
                    "document",
                    models.TextField(
                        validators=[
                            undine.persisted_queries.validators.validate_document,
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "persisted query",
                "verbose_name_plural": "persisted queries",
            },
        ),
    ]
