"""
This file contains all possible HTTP error codes that undine returns.
The module should be used like this:

>>> from undine.errors import error_codes
>>>
>>> error_codes.MODEL_NOT_FOUND

Do not put anything else in this file!
Codes should be sorted alphabetically.
"""

CONTENT_TYPE_MISSING = "CONTENT_TYPE_MISSING"
DECODING_ERROR = "DECODING_ERROR"
EMPTY_QUERY = "EMPTY_QUERY"
FILE_NOT_FOUND = "FILE_NOT_FOUND"
GRAPHQL_CANT_CREATE_ENUM = "GRAPHQL_CANT_CREATE_ENUM"
GRAPHQL_CONVERSION_ERROR = "GRAPHQL_CONVERSION_ERROR"
GRAPHQL_DUPLICATE_ENUM = "GRAPHQL_DUPLICATE_ENUM"
INVALID_INPUT_DATA = "INVALID_INPUT_DATA"
INVALID_OPERATION_FOR_METHOD = "INVALID_OPERATION_FOR_METHOD"
INVALID_ORDER_DATA = "INVALID_ORDER_DATA"
LOOKUP_FIELD_MISSING = "LOOKUP_FIELD_MISSING"
LOOKUP_VALUE_MISSING = "LOOKUP_VALUE_MISSING"
MISSING_FILE_MAP = "MISSING_FILE_MAP"
MISSING_OPERATIONS = "MISSING_OPERATIONS"
MODEL_CONSTRAINT_VIOLATION = "MODEL_CONSTRAINT_VIOLATION"
MODEL_MULTIPLE_OBJECTS = "MODEL_MULTIPLE_OBJECTS"
MODEL_NOT_FOUND = "MODEL_NOT_FOUND"
NODE_ID_NOT_GLOBAL_ID = "NODE_ID_NOT_GLOBAL_ID"
NODE_INTERFACE_MISSING = "NODE_INTERFACE_MISSING"
NODE_INVALID_GLOBAL_ID = "NODE_INVALID_GLOBAL_ID"
NODE_MISSING_OBJECT_TYPE = "NODE_MISSING_OBJECT_TYPE"
NODE_QUERY_TYPE_ID_FIELD_MISSING = "NODE_QUERY_TYPE_ID_FIELD_MISSING"
NODE_QUERY_TYPE_MISSING = "NODE_QUERY_TYPE_MISSING"
PERMISSION_DENIED = "PERMISSION_DENIED"
UNSUPPORTED_CONTENT_TYPE = "UNSUPPORTED_CONTENT_TYPE"
VALIDATION_ERROR = "VALIDATION_ERROR"
