from __future__ import annotations

import ast
import dataclasses
import shutil
from contextlib import suppress
from pathlib import Path
from typing import TYPE_CHECKING, Any

from django.conf import settings
from django.core.management import BaseCommand, CommandError

if TYPE_CHECKING:
    from django.core.management import CommandParser


class Command(BaseCommand):
    help = "Generate yml test files from mypy test cases in `tests/test_mypy/cases/*.py`"

    def add_arguments(self, parser: CommandParser) -> None:
        parser.add_argument(
            "--silent",
            action="store_true",
            default=False,
            help="Don't send messages to stdout",
        )

    def handle(self, *args: Any, **options: Any) -> None:
        silent: bool = options["silent"]

        # Make sure the cases directory is empty
        with suppress(OSError):
            shutil.rmtree(CASES_DIR)
        CASES_DIR.mkdir(parents=True, exist_ok=True)

        for case_path in discover_cases(TESTS_DIR):
            case = load_case(case_path)
            contents = emit_mypy_yml(case)
            case.yml_path.write_text(contents, encoding="utf-8")
            if not silent:
                self.stdout.write(self.style.SUCCESS(f"Wrote {case.yml_path}"))


RESERVED_SECTION_KEYS = frozenset({"case"})

YAML_OPTION_ORDER = (
    "mypy_config",
    "out",
    "regex",
    "disable_cache",
    "env",
    "skip",
    "expect_fail",
    "parametrized",
    "files",
)
ALLOWED_OPTION_KEYS = frozenset(YAML_OPTION_ORDER)


SCHEMA_COMMENT = (
    "# yaml-language-server: $schema=https://raw.githubusercontent.com/"
    "typeddjango/pytest-mypy-plugins/master/pytest_mypy_plugins/schema.json"
)

GENERATED_WARNING_LINES = (
    "# WARNING: This file is generated by `just mypy-test-gen`.",
    "# Do not edit by hand; edit `tests/test_mypy/*.py` files and re-run the command.",
)

BASE_DIR = Path(settings.BASE_DIR)
REPO_ROOT = BASE_DIR.parent
TESTS_DIR = REPO_ROOT / "tests" / "test_mypy"
CASES_DIR = TESTS_DIR / "cases"


@dataclasses.dataclass(frozen=True, slots=True, kw_only=True)
class MypyCase:
    name: str
    main: str
    options: dict[str, str]
    yml_path: Path


def discover_cases(cases_dir: Path) -> list[Path]:
    if not cases_dir.is_dir():
        msg = f"cases directory not found: {cases_dir}"
        raise CommandError(msg)

    paths = sorted(p for p in cases_dir.glob("*.py") if p.name != "__init__.py")
    if not paths:
        msg = f"no case files in {cases_dir}"
        raise CommandError(msg)

    return paths


def load_case(path: Path) -> MypyCase:
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source, filename=str(path))
    doc = ast.get_docstring(tree, clean=False)
    if doc is None:
        msg = f"{path}: missing module docstring"
        raise CommandError(msg)

    options = parse_docstring_sections(doc)
    validate_option_keys(path, options)
    mypy_config = options.get("mypy_config", "")
    if not mypy_config:
        msg = f"{path}: missing or empty ### mypy_config section"
        raise CommandError(msg)

    main = extract_main_after_module_docstring(source, tree)
    if not main.strip():
        msg = f"{path}: main body is empty after module docstring"
        raise CommandError(msg)

    name = path.stem
    case_path = CASES_DIR / f"test_{name}.yml"
    return MypyCase(name=name, main=main, options=options, yml_path=case_path)


def parse_docstring_sections(doc: str) -> dict[str, str]:
    lines = doc.splitlines()
    sections: dict[str, list[str]] = {}
    current_key: str | None = None

    for line in lines:
        stripped = line.strip()

        if stripped.startswith("###"):
            header = stripped[3:].strip()
            if not header:
                msg = "empty ### section header"
                raise CommandError(msg)

            key = header.split(None, 1)[0]

            if key == "main":
                msg = (
                    "### main is reserved; put the checked code in the module body "
                    'after the docstring (that becomes "main" in the YAML)'
                )
                raise CommandError(msg)

            if key in RESERVED_SECTION_KEYS:
                msg = f"### {key} is reserved (set by the generator, not the docstring)"
                raise CommandError(msg)

            if key in sections:
                msg = f"duplicate ### {key} section"
                raise CommandError(msg)

            current_key = key
            sections[key] = []
            continue

        if current_key is not None:
            sections[current_key].append(line)

    # Skip mypy tests by default because they are slow
    sections.setdefault("skip", ['os.getenv("RUN_MYPY_TESTS", "0") == "0"'])

    result: dict[str, str] = {}
    for key, body_lines in sections.items():
        text = "\n".join(body_lines).strip("\n")
        if text:
            result[key] = text

    return result


def validate_option_keys(path: Path, options: dict[str, str]) -> None:
    unknown = sorted(set(options) - ALLOWED_OPTION_KEYS)
    if unknown:
        names = ", ".join(unknown)
        allowed = ", ".join(YAML_OPTION_ORDER)
        msg = f"{path}: unknown ### section(s): {names}; allowed: {allowed}"
        raise CommandError(msg)


def extract_main_after_module_docstring(source: str, tree: ast.Module) -> str:
    body = tree.body
    if not body:
        msg = "empty module"
        raise CommandError(msg)

    first = body[0]
    if not (
        isinstance(first, ast.Expr) and isinstance(first.value, ast.Constant) and isinstance(first.value.value, str)
    ):
        msg = "module must start with a module docstring"
        raise CommandError(msg)

    end_lineno = first.end_lineno
    if end_lineno is None:
        msg = "docstring node missing end_lineno"
        raise CommandError(msg)

    lines = source.splitlines()
    rest = lines[end_lineno:]
    if not rest:
        return ""

    joined = "\n".join(rest)
    if source.endswith("\n"):
        joined += "\n"

    return joined


def emit_mypy_yml(case: MypyCase) -> str:
    parts: list[str] = [SCHEMA_COMMENT, *GENERATED_WARNING_LINES]
    parts.append(f"- case: {case.name}")
    parts.extend(emit_yaml_block("main", case.main))
    for key in YAML_OPTION_ORDER:
        if key in case.options:
            parts.extend(emit_yaml_block(key, case.options[key]))
    parts.append("")
    return "\n".join(parts)


def emit_yaml_block(key: str, content: str) -> list[str]:
    result = [f"  {key}: |"]
    result.extend(f"    {line}" for line in content.splitlines())
    if not content:
        result.append("    ")
    return result
