"""
This file contains all possible HTTP error codes that undine returns.
The module should be used like this:

>>> from undine import error_codes
>>>
>>> error_codes.MODEL_NOT_FOUND

Do not put anything else in this file!
Codes should be sorted alphabetically.
"""

CONTENT_TYPE_MISSING = "CONTENT_TYPE_MISSING"
DECODING_ERROR = "DECODING_ERROR"
EMPTY_QUERY = "EMPTY_QUERY"
FILE_NOT_FOUND = "FILE_NOT_FOUND"
INVALID_INPUT_DATA = "INVALID_INPUT_DATA"
LOOKUP_FIELD_MISSING = "LOOKUP_FIELD_MISSING"
LOOKUP_VALUE_MISSING = "LOOKUP_VALUE_MISSING"
MISSING_FILE_MAP = "MISSING_FILE_MAP"
MISSING_OPERATIONS = "MISSING_OPERATIONS"
MODEL_MULTIPLE_OBJECTS = "MODEL_MULTIPLE_OBJECTS"
MODEL_NOT_FOUND = "MODEL_NOT_FOUND"
MODEL_UNIQUE_CONSTRAINT_VIOLATION = "MODEL_UNIQUE_CONSTRAINT_VIOLATION"
UNSUPPORTED_CONTENT_TYPE = "UNSUPPORTED_CONTENT_TYPE"
