# Generated by Django 5.2.16 on 2026-07-20 20:07

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

if TYPE_CHECKING:
    from .. import models  # noqa: TID252


DIMENSION: dict[str, Any] = {
    "size": "small",
    "weight": 1.0,
    "unit": "kg",
}

USER: dict[str, Any] = {
    "email": "support@apollographql.com",
    "name": "Jane Smith",
    "total_products_created": 1337,
    "years_of_employment": 10,
}

DEPRECATED_PRODUCT: dict[str, Any] = {
    "sku": "apollo-federation-v1",
    "package": "@apollo/federation-v1",
    "reason": "Migrate to Federation V2",
}

PRODUCTS_RESEARCH: list[dict[str, Any]] = [
    {
        "study": {"case_number": "1234", "description": "Federation Study"},
        "outcome": None,
    },
    {
        "study": {"case_number": "1235", "description": "Studio Study"},
        "outcome": None,
    },
]

PRODUCTS: list[dict[str, Any]] = [
    {
        "id": "apollo-federation",
        "sku": "federation",
        "package": "@apollo/federation",
        "variation": {"id": "OSS"},
        "dimensions": DIMENSION,
        "research": [PRODUCTS_RESEARCH[0]],
        "notes": None,
    },
    {
        "id": "apollo-studio",
        "sku": "studio",
        "package": "",
        "variation": {"id": "platform"},
        "dimensions": DIMENSION,
        "research": [PRODUCTS_RESEARCH[1]],
        "notes": None,
    },
]

INVENTORY = {
    "id": "apollo-oss",
    "deprecated_products": [DEPRECATED_PRODUCT],
}


def seed(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    ProductDimension: type[models.ProductDimension] = apps.get_model("products", "ProductDimension")
    ProductVariation: type[models.ProductVariation] = apps.get_model("products", "ProductVariation")
    CaseStudy: type[models.CaseStudy] = apps.get_model("products", "CaseStudy")
    ProductResearch: type[models.ProductResearch] = apps.get_model("products", "ProductResearch")
    Product: type[models.Product] = apps.get_model("products", "Product")
    DeprecatedProduct: type[models.DeprecatedProduct] = apps.get_model("products", "DeprecatedProduct")
    Inventory: type[models.Inventory] = apps.get_model("products", "Inventory")
    User: type[models.User] = apps.get_model("products", "User")

    User.objects.create(**USER)

    dimension = ProductDimension.objects.create(**DIMENSION)

    research_instances = []
    for entry in PRODUCTS_RESEARCH:
        study = CaseStudy.objects.create(**entry["study"])
        research = ProductResearch.objects.create(study=study, outcome=entry["outcome"])
        research_instances.append(research)

    for index, entry in enumerate(PRODUCTS):
        variation = ProductVariation.objects.create(id=entry["variation"]["id"])
        product = Product.objects.create(
            id=entry["id"],
            sku=entry["sku"],
            package=entry["package"],
            variation=variation,
            dimensions=dimension,
            notes=entry["notes"],
        )
        product.research.add(research_instances[index])

    deprecated = DeprecatedProduct.objects.create(**DEPRECATED_PRODUCT)
    inventory = Inventory.objects.create(id=INVENTORY["id"])
    inventory.deprecated_products.add(deprecated)


def clear(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    ProductDimension: type[models.ProductDimension] = apps.get_model("products", "ProductDimension")
    ProductVariation: type[models.ProductVariation] = apps.get_model("products", "ProductVariation")
    CaseStudy: type[models.CaseStudy] = apps.get_model("products", "CaseStudy")
    ProductResearch: type[models.ProductResearch] = apps.get_model("products", "ProductResearch")
    Product: type[models.Product] = apps.get_model("products", "Product")
    DeprecatedProduct: type[models.DeprecatedProduct] = apps.get_model("products", "DeprecatedProduct")
    Inventory: type[models.Inventory] = apps.get_model("products", "Inventory")
    User: type[models.User] = apps.get_model("products", "User")

    User.objects.all().delete()
    ProductVariation.objects.all().delete()
    ProductDimension.objects.all().delete()
    CaseStudy.objects.all().delete()
    ProductResearch.objects.all().delete()
    Product.objects.all().delete()
    DeprecatedProduct.objects.all().delete()
    Inventory.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            code=seed,
            reverse_code=clear,
        ),
    ]
