from __future__ import annotations

import dataclasses
import decimal
import types
from enum import Enum
from importlib.util import find_spec
from pathlib import Path
from typing import TYPE_CHECKING, Any, ForwardRef, NamedTuple, get_origin

from django.core.management import BaseCommand, CommandError
from django.db.models import Model
from graphql import GraphQLInputObjectType, GraphQLType, Undefined

from undine import MutationType
from undine.converters import convert_graphql_type_to_python_type, convert_model_field_to_python_type
from undine.dataclasses import LazyLambda, TypeRef
from undine.exceptions import (
    MutationInputDataTypesModuleImportError,
    MutationInputDataTypesModuleNoParentError,
    MutationInputDataTypesModuleNotOverridableError,
    MutationInputDataTypesModuleNotSetError,
    MutationInputDataTypesModuleParentNotPackageError,
    MutationTypeInputDataTypesNoMutationTypesError,
)
from undine.parsers import parse_return_annotation
from undine.settings import undine_settings
from undine.typing import TypedDictType
from undine.utils.graphql.undine_extensions import get_undine_mutation_type
from undine.utils.reflection import get_flattened_generic_params, is_subclass, is_union_origin

if TYPE_CHECKING:
    from graphql import GraphQLSchema

    from undine import Input


__all__ = [
    "find_mutation_input_data_typing_file",
    "generate_mutation_input_data_types",
]


class Command(BaseCommand):
    help = "Generate TypedDict definitions for the input data passed to MutationType hooks."

    def handle(self, *args: Any, **options: Any) -> None:
        try:
            target_path = find_mutation_input_data_typing_file()

            try:
                content = generate_mutation_input_data_types()

            except MutationTypeInputDataTypesNoMutationTypesError:
                self.stdout.write("No MutationTypes found in schema")
                if target_path.exists():  # pragma: no branch
                    self.stdout.write(f"Removing {target_path}")
                    target_path.unlink(missing_ok=True)
                return

            target_path.parent.mkdir(parents=True, exist_ok=True)
            target_path.write_text(content, encoding="utf-8")
            self.stdout.write(f"Wrote {target_path}")

        except Exception as error:
            raise CommandError(str(error)) from error


MARKER = "# Generated by undine. DO NOT EDIT. Regenerate with `python manage.py generate_mutation_input_types`."


# --- Public API ---------------------------------------------------------------------------------


def generate_mutation_input_data_types() -> str:
    mutation_types = _discover_mutation_types(undine_settings.SCHEMA)
    if not mutation_types:
        raise MutationTypeInputDataTypesNoMutationTypesError

    collector = TypeCollector()
    class_blocks: list[str] = []

    for mutation_type in mutation_types:
        class_blocks.extend((
            _render_typed_dict(mutation_type, collector=collector),
            _render_typed_dict(mutation_type, include_input_only=False, collector=collector),
        ))

    return _assemble_file(class_blocks, collector)


def find_mutation_input_data_typing_file() -> Path:
    module_path = undine_settings.MUTATION_INPUT_DATA_TYPES_MODULE
    if not module_path:
        raise MutationInputDataTypesModuleNotSetError

    parent_path, _, module_name = module_path.rpartition(".")

    if not parent_path:
        raise MutationInputDataTypesModuleNoParentError(module_path=module_path)

    try:
        parent_spec = find_spec(parent_path)
    except Exception as error:
        raise MutationInputDataTypesModuleImportError(
            parent_path=parent_path,
            module_path=module_path,
            error=str(error),
        ) from error

    if parent_spec is None or not parent_spec.submodule_search_locations:
        raise MutationInputDataTypesModuleParentNotPackageError(parent_path=parent_path, module_path=module_path)

    parent_dir = Path(next(iter(parent_spec.submodule_search_locations)))
    target_path = parent_dir / f"{module_name}.py"

    if not target_path.exists():
        return target_path

    with target_path.open(encoding="utf-8") as fh:
        first_line = fh.readline()

    if first_line.strip() != MARKER:
        raise MutationInputDataTypesModuleNotOverridableError(target_path=target_path, marker=MARKER)

    return target_path


# --- Discovery ----------------------------------------------------------------------------------


def _discover_mutation_types(schema: GraphQLSchema) -> list[type[MutationType]]:
    seen: set[type[MutationType]] = set()

    for graphql_type in schema.type_map.values():
        if not isinstance(graphql_type, GraphQLInputObjectType):
            continue

        mutation_type = get_undine_mutation_type(graphql_type)
        if mutation_type is not None:
            seen.add(mutation_type)

    return sorted(seen, key=lambda mt: mt.__schema_name__)


# --- Rendering ----------------------------------------------------------------------------------


def _render_typed_dict(
    mutation_type: type[MutationType],
    *,
    include_input_only: bool = True,
    collector: TypeCollector,
) -> str:
    suffix = "FullInputData" if include_input_only else "InputData"
    class_name = f"{mutation_type.__schema_name__}{suffix}"

    lines = [f"class {class_name}(TypedDict):"]

    field_lines: list[str] = []
    for input_field in mutation_type.__input_map__.values():
        if not include_input_only and input_field.input_only:
            continue

        field_line = _render_field(input_field, include_input_only=include_input_only, collector=collector)
        field_lines.append(field_line)

    if not field_lines:
        lines.append("    pass")
    else:
        lines.extend(f"    {line}" for line in field_lines)

    return "\n".join(lines)


def _render_field(input_field: Input, *, include_input_only: bool, collector: TypeCollector) -> str:
    key = input_field.name
    value_type = _render_value_type(input_field, include_input_only=include_input_only, collector=collector)

    if input_field.many:
        value_type = f"list[{value_type}]"

    required, nullable = _calculate_required_and_nullable(input_field)
    if nullable:
        value_type = f"{value_type} | None"

    if not required:
        collector.add_from("typing", "NotRequired")
        value_type = f"NotRequired[{value_type}]"

    return f"{key}: {value_type}"


def _render_value_type(input_field: Input, *, include_input_only: bool, collector: TypeCollector) -> str:
    ref = input_field.ref

    if isinstance(ref, LazyLambda):
        ref = ref.callback()

    if isinstance(ref, type) and issubclass(ref, MutationType):
        suffix = "FullInputData" if include_input_only else "InputData"
        return f"{ref.__schema_name__}{suffix}"

    if isinstance(ref, type) and issubclass(ref, Model):
        return collector.add_class(ref)

    if isinstance(ref, types.FunctionType):
        py_type = parse_return_annotation(ref)
        return _format_python_type(py_type, collector=collector)

    if isinstance(ref, GraphQLType):
        converted_ref = convert_graphql_type_to_python_type(ref)
        return _format_python_type(converted_ref, collector=collector, define=True)

    if input_field.hidden and input_field.default_value is not Undefined and input_field.default_value is not None:
        return _format_python_type(type(input_field.default_value), collector=collector)

    if isinstance(ref, TypeRef):
        return _format_python_type(ref.value, collector=collector)

    py_type = convert_model_field_to_python_type(ref)
    return _format_python_type(py_type, collector=collector)


class RequiredAndNullable(NamedTuple):
    required: bool
    nullable: bool


def _calculate_required_and_nullable(input_field: Input) -> RequiredAndNullable:
    default = input_field.default_value

    if input_field.hidden:
        if isinstance(input_field.ref, types.FunctionType):
            return RequiredAndNullable(required=True, nullable=False)
        if default is Undefined:
            return RequiredAndNullable(required=False, nullable=False)
        if default is None:
            return RequiredAndNullable(required=True, nullable=True)
        return RequiredAndNullable(required=True, nullable=False)

    if input_field.required:
        return RequiredAndNullable(required=True, nullable=False)
    if default is Undefined:
        return RequiredAndNullable(required=False, nullable=False)
    if default is None:
        return RequiredAndNullable(required=True, nullable=True)
    return RequiredAndNullable(required=True, nullable=False)


# --- Python type formatting ---------------------------------------------------------------------


def _format_python_type(py_type: Any, *, collector: TypeCollector, define: bool = False) -> str:  # noqa: PLR0911,C901
    if isinstance(py_type, ForwardRef):  # pragma: no cover
        py_type = py_type.evaluate()

    if py_type is None or py_type is types.NoneType:
        return "None"

    if py_type is Any:
        collector.add_from("typing", "Any")
        return "Any"

    origin = get_origin(py_type)
    if is_union_origin(origin):
        args = get_flattened_generic_params(py_type)
        rendered = [_format_python_type(a, collector=collector, define=define) for a in args]
        return " | ".join(rendered)

    if origin is not None:
        origin_str = _format_python_type(origin, collector=collector, define=define)
        args = get_flattened_generic_params(py_type)
        rendered_args = ", ".join(_format_python_type(a, collector=collector, define=define) for a in args)
        return f"{origin_str}[{rendered_args}]"

    if not isinstance(py_type, type):
        collector.add_from("typing", "Any")
        return "Any"

    if py_type.__module__ == "builtins":
        return py_type.__name__

    if py_type is decimal.Decimal:
        collector.add_from("decimal", "Decimal")
        return "Decimal"

    if py_type.__module__ == "datetime":
        collector.add_module("datetime")
        return f"datetime.{py_type.__name__}"

    if py_type.__module__ == "uuid":
        collector.add_module("uuid")
        return f"uuid.{py_type.__name__}"

    if define and isinstance(py_type, TypedDictType):  # type: ignore[misc]
        collector.add_definition_from_typed_dict(py_type)
        return py_type.__name__

    if define and is_subclass(py_type, Enum):
        collector.add_definition_from_enum(py_type)
        return py_type.__name__

    return collector.add_class(py_type)


# --- Imports ------------------------------------------------------------------------------------


@dataclasses.dataclass
class TypeCollector:
    """Collects types to be imported and types to be defined for the generated file."""

    modules: set[str] = dataclasses.field(default_factory=set)
    from_imports: dict[str, set[str]] = dataclasses.field(default_factory=dict)
    type_definitions: set[str] = dataclasses.field(default_factory=set)
    require_enum: bool = False
    max_line_length: int = 120

    def add_module(self, module: str) -> None:
        self.modules.add(module)

    def add_from(self, module: str, name: str) -> None:
        self.from_imports.setdefault(module, set()).add(name)

    def add_class(self, cls: type) -> str:
        module = cls.__module__
        qualname = cls.__qualname__
        top = qualname.split(".")[0]
        self.add_from(module, top)
        return qualname

    def add_definition_from_typed_dict(self, typed_dict: TypedDictType) -> None:
        definition = "class " + typed_dict.__name__ + "(TypedDict):"
        for key, value in typed_dict.__annotations__.items():
            definition += f"\n    {key}: {_format_python_type(value, collector=self)}"
        self.type_definitions.add(definition)

    def add_definition_from_enum(self, enum_type: type[Enum]) -> None:
        self.require_enum = True
        definition = "class " + enum_type.__name__ + "(Enum):"
        for member in enum_type.__members__.values():
            definition += f"\n    {member.name} = {member.value}"
        self.type_definitions.add(definition)

    def render_header(self) -> str:
        header = MARKER + "\n# isort: off\nfrom __future__ import annotations\n\n"

        if self.require_enum:
            header += "from enum import Enum\n"

        if self.from_imports or self.modules:
            header += "from typing import TYPE_CHECKING, TypedDict\n\nif TYPE_CHECKING:\n" + self.render_imports()
        else:
            header += "from typing import TypedDict"

        return header

    def render_imports(self) -> str:
        indent: str = "    "

        lines: list[str] = [f"{indent}import {module}" for module in sorted(self.modules)]
        for module in sorted(self.from_imports):
            names = sorted(self.from_imports[module])
            single = f"{indent}from {module} import {', '.join(names)}"
            if len(single) <= self.max_line_length:
                lines.append(single)
                continue

            lines.append(f"{indent}from {module} import (")
            lines.extend(f"{indent}    {name}," for name in names)
            lines.append(f"{indent})")

        return "\n".join(lines)


# --- Assembly -----------------------------------------------------------------------------------


def _assemble_file(class_blocks: list[str], collector: TypeCollector) -> str:
    header = collector.render_header()
    parts = [header, *sorted(collector.type_definitions), *class_blocks]

    body = "\n\n\n".join(parts)
    return body + "\n"
