# Generated by undine. DO NOT EDIT. Regenerate with `python manage.py generate_mutation_input_types`.
# isort: off
from __future__ import annotations

from typing import TYPE_CHECKING, TypedDict

if TYPE_CHECKING:
    import datetime
    import uuid
    from decimal import Decimal
    from example_project.app.models import (
        AcceptanceCriteria,
        Comment,
        Person,
        Project,
        Report,
        ServiceRequest,
        Task,
        TaskObjective,
        TaskResult,
        TaskStep,
        Team,
    )
    from example_project.app.mutations import CustomInput
    from typing import NotRequired


class CommentCreateMutationTypeFullInputData(TypedDict):
    commenter: Person | None
    contents: str
    target: str


class CommentCreateMutationTypeInputData(TypedDict):
    commenter: Person | None
    contents: str
    target: str


class CommentInputFullInputData(TypedDict):
    commenter: NotRequired[PersonInputFullInputData]
    contents: NotRequired[str]
    pk: NotRequired[int]


class CommentInputInputData(TypedDict):
    commenter: NotRequired[PersonInputInputData]
    contents: NotRequired[str]
    pk: NotRequired[int]


class CommentTargetProjectInputFullInputData(TypedDict):
    comments: NotRequired[list[Comment]]
    name: NotRequired[str]
    pk: NotRequired[int]
    tasks: NotRequired[list[Task]]
    team: NotRequired[Team]


class CommentTargetProjectInputInputData(TypedDict):
    comments: NotRequired[list[Comment]]
    name: NotRequired[str]
    pk: NotRequired[int]
    tasks: NotRequired[list[Task]]
    team: NotRequired[Team]


class CommentTargetReportInputFullInputData(TypedDict):
    comments: NotRequired[list[Comment]]
    content: NotRequired[str]
    name: NotRequired[str]
    tasks: NotRequired[list[Task]]


class CommentTargetReportInputInputData(TypedDict):
    comments: NotRequired[list[Comment]]
    content: NotRequired[str]
    name: NotRequired[str]
    tasks: NotRequired[list[Task]]


class CommentTargetTaskInputFullInputData(TypedDict):
    acceptancecriteria: NotRequired[list[AcceptanceCriteria]]
    assignees: NotRequired[list[Person]]
    attachment: NotRequired[str]
    check_time: NotRequired[datetime.time]
    comments: NotRequired[list[Comment]]
    contact_email: NotRequired[str]
    demo_url: NotRequired[str]
    done: NotRequired[bool]
    due_by: NotRequired[datetime.date]
    external_uuid: NotRequired[uuid.UUID]
    extra_data: NotRequired[dict[str, str]]
    image: NotRequired[str]
    name: NotRequired[str]
    objective: NotRequired[TaskObjective]
    pk: NotRequired[int]
    points: NotRequired[int]
    progress: NotRequired[Decimal]
    project: NotRequired[Project]
    related_tasks: NotRequired[list[Task]]
    reports: NotRequired[list[Report]]
    request: NotRequired[ServiceRequest]
    result: NotRequired[TaskResult]
    steps: NotRequired[list[TaskStep]]
    type: NotRequired[str]
    worked_hours: NotRequired[datetime.timedelta]


class CommentTargetTaskInputInputData(TypedDict):
    acceptancecriteria: NotRequired[list[AcceptanceCriteria]]
    assignees: NotRequired[list[Person]]
    attachment: NotRequired[str]
    check_time: NotRequired[datetime.time]
    comments: NotRequired[list[Comment]]
    contact_email: NotRequired[str]
    demo_url: NotRequired[str]
    done: NotRequired[bool]
    due_by: NotRequired[datetime.date]
    external_uuid: NotRequired[uuid.UUID]
    extra_data: NotRequired[dict[str, str]]
    image: NotRequired[str]
    name: NotRequired[str]
    objective: NotRequired[TaskObjective]
    pk: NotRequired[int]
    points: NotRequired[int]
    progress: NotRequired[Decimal]
    project: NotRequired[Project]
    related_tasks: NotRequired[list[Task]]
    reports: NotRequired[list[Report]]
    request: NotRequired[ServiceRequest]
    result: NotRequired[TaskResult]
    steps: NotRequired[list[TaskStep]]
    type: NotRequired[str]
    worked_hours: NotRequired[datetime.timedelta]


class PersonInputFullInputData(TypedDict):
    email: NotRequired[str]
    name: NotRequired[str]
    pk: NotRequired[int]
    teams: NotRequired[list[Team]]


class PersonInputInputData(TypedDict):
    email: NotRequired[str]
    name: NotRequired[str]
    pk: NotRequired[int]
    teams: NotRequired[list[Team]]


class ProjectInputFullInputData(TypedDict):
    comments: NotRequired[list[Comment]]
    name: NotRequired[str]
    pk: NotRequired[int]
    team: NotRequired[TeamInputFullInputData]


class ProjectInputInputData(TypedDict):
    comments: NotRequired[list[Comment]]
    name: NotRequired[str]
    pk: NotRequired[int]
    team: NotRequired[TeamInputInputData]


class ReportInputFullInputData(TypedDict):
    comments: NotRequired[list[Comment]]
    content: NotRequired[str]
    name: NotRequired[str]


class ReportInputInputData(TypedDict):
    comments: NotRequired[list[Comment]]
    content: NotRequired[str]
    name: NotRequired[str]


class ServiceRequestInputFullInputData(TypedDict):
    details: NotRequired[str]
    pk: NotRequired[int]
    submitted_at: NotRequired[datetime.date]


class ServiceRequestInputInputData(TypedDict):
    details: NotRequired[str]
    pk: NotRequired[int]
    submitted_at: NotRequired[datetime.date]


class TaskCreateMutationTypeFullInputData(TypedDict):
    acceptancecriteria: NotRequired[list[AcceptanceCriteria]]
    assignees: NotRequired[list[PersonInputFullInputData]]
    attachment: str | None
    check_time: datetime.time | None
    comments: NotRequired[list[CommentInputFullInputData]]
    contact_email: str | None
    current_user: int | None
    custom: CustomInput
    demo_url: str | None
    done: bool
    due_by: datetime.date | None
    external_uuid: uuid.UUID | None
    extra_data: dict[str, str] | None
    image: str | None
    input_only: bool
    name: str
    objective: NotRequired[TaskObjective]
    points: int | None
    progress: Decimal
    project: NotRequired[ProjectInputFullInputData]
    related_tasks: NotRequired[list[TaskInputFullInputData]]
    reports: NotRequired[list[ReportInputFullInputData]]
    request: NotRequired[ServiceRequestInputFullInputData]
    result: NotRequired[TaskResultInputFullInputData]
    steps: NotRequired[list[TaskStepInputFullInputData]]
    type: str
    worked_hours: NotRequired[datetime.timedelta]


class TaskCreateMutationTypeInputData(TypedDict):
    acceptancecriteria: NotRequired[list[AcceptanceCriteria]]
    assignees: NotRequired[list[PersonInputInputData]]
    attachment: str | None
    check_time: datetime.time | None
    comments: NotRequired[list[CommentInputInputData]]
    contact_email: str | None
    demo_url: str | None
    done: bool
    due_by: datetime.date | None
    external_uuid: uuid.UUID | None
    extra_data: dict[str, str] | None
    image: str | None
    name: str
    objective: NotRequired[TaskObjective]
    points: int | None
    progress: Decimal
    project: NotRequired[ProjectInputInputData]
    related_tasks: NotRequired[list[TaskInputInputData]]
    reports: NotRequired[list[ReportInputInputData]]
    request: NotRequired[ServiceRequestInputInputData]
    result: NotRequired[TaskResultInputInputData]
    steps: NotRequired[list[TaskStepInputInputData]]
    type: str
    worked_hours: NotRequired[datetime.timedelta]


class TaskDeleteMutationTypeFullInputData(TypedDict):
    pk: int


class TaskDeleteMutationTypeInputData(TypedDict):
    pk: int


class TaskInputFullInputData(TypedDict):
    acceptancecriteria: NotRequired[list[AcceptanceCriteria]]
    assignees: NotRequired[list[PersonInputFullInputData]]
    attachment: NotRequired[str]
    check_time: NotRequired[datetime.time]
    comments: NotRequired[list[CommentInputFullInputData]]
    contact_email: NotRequired[str]
    demo_url: NotRequired[str]
    done: NotRequired[bool]
    due_by: NotRequired[datetime.date]
    external_uuid: NotRequired[uuid.UUID]
    extra_data: NotRequired[dict[str, str]]
    image: NotRequired[str]
    name: NotRequired[str]
    objective: NotRequired[TaskObjective]
    pk: NotRequired[int]
    points: NotRequired[int]
    progress: NotRequired[Decimal]
    project: NotRequired[ProjectInputFullInputData]
    related_tasks: NotRequired[TaskInputFullInputData]
    reports: NotRequired[list[ReportInputFullInputData]]
    request: NotRequired[ServiceRequestInputFullInputData]
    result: NotRequired[TaskResultInputFullInputData]
    steps: NotRequired[list[TaskStepInputFullInputData]]
    type: NotRequired[str]
    worked_hours: NotRequired[datetime.timedelta]


class TaskInputInputData(TypedDict):
    acceptancecriteria: NotRequired[list[AcceptanceCriteria]]
    assignees: NotRequired[list[PersonInputInputData]]
    attachment: NotRequired[str]
    check_time: NotRequired[datetime.time]
    comments: NotRequired[list[CommentInputInputData]]
    contact_email: NotRequired[str]
    demo_url: NotRequired[str]
    done: NotRequired[bool]
    due_by: NotRequired[datetime.date]
    external_uuid: NotRequired[uuid.UUID]
    extra_data: NotRequired[dict[str, str]]
    image: NotRequired[str]
    name: NotRequired[str]
    objective: NotRequired[TaskObjective]
    pk: NotRequired[int]
    points: NotRequired[int]
    progress: NotRequired[Decimal]
    project: NotRequired[ProjectInputInputData]
    related_tasks: NotRequired[TaskInputInputData]
    reports: NotRequired[list[ReportInputInputData]]
    request: NotRequired[ServiceRequestInputInputData]
    result: NotRequired[TaskResultInputInputData]
    steps: NotRequired[list[TaskStepInputInputData]]
    type: NotRequired[str]
    worked_hours: NotRequired[datetime.timedelta]


class TaskResultInputFullInputData(TypedDict):
    details: NotRequired[str]
    pk: NotRequired[int]
    time_used: NotRequired[datetime.timedelta]


class TaskResultInputInputData(TypedDict):
    details: NotRequired[str]
    pk: NotRequired[int]
    time_used: NotRequired[datetime.timedelta]


class TaskStepInputFullInputData(TypedDict):
    done: NotRequired[bool]
    name: NotRequired[str]
    pk: NotRequired[int]


class TaskStepInputInputData(TypedDict):
    done: NotRequired[bool]
    name: NotRequired[str]
    pk: NotRequired[int]


class TeamInputFullInputData(TypedDict):
    members: NotRequired[list[Person]]
    name: NotRequired[str]
    pk: NotRequired[int]


class TeamInputInputData(TypedDict):
    members: NotRequired[list[Person]]
    name: NotRequired[str]
    pk: NotRequired[int]
