# Generated by Django 5.1.2 on 2024-10-30 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForwardManyToManyForRelated",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ForwardManyToOneForRelated",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ForwardOneToOneForRelated",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ForwardManyToMany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "forward_many_to_many_fields",
                    models.ManyToManyField(
                        related_name="forward_many_to_many_rels",
                        to="app.forwardmanytomanyforrelated",
                    ),
                ),
                (
                    "forward_many_to_one_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forward_many_to_many_rels",
                        to="app.forwardmanytooneforrelated",
                    ),
                ),
                (
                    "forward_one_to_one_field",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forward_many_to_many_rel",
                        to="app.forwardonetooneforrelated",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ForwardManyToOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "forward_many_to_many_fields",
                    models.ManyToManyField(
                        related_name="forward_many_to_one_rels",
                        to="app.forwardmanytomanyforrelated",
                    ),
                ),
                (
                    "forward_many_to_one_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forward_many_to_one_rels",
                        to="app.forwardmanytooneforrelated",
                    ),
                ),
                (
                    "forward_one_to_one_field",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forward_many_to_one_rel",
                        to="app.forwardonetooneforrelated",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ForwardOneToOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "forward_many_to_many_fields",
                    models.ManyToManyField(
                        related_name="forward_one_to_one_rels",
                        to="app.forwardmanytomanyforrelated",
                    ),
                ),
                (
                    "forward_many_to_one_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forward_one_to_one_rels",
                        to="app.forwardmanytooneforrelated",
                    ),
                ),
                (
                    "forward_one_to_one_field",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forward_one_to_one_rel",
                        to="app.forwardonetooneforrelated",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Example",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "named_relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="app.task",
                    ),
                ),
                ("symmetrical_field", models.ManyToManyField(to="app.example")),
                (
                    "forward_many_to_many_fields",
                    models.ManyToManyField(related_name="example_rels", to="app.forwardmanytomany"),
                ),
                (
                    "forward_many_to_one_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="example_rels",
                        to="app.forwardmanytoone",
                    ),
                ),
                (
                    "forward_one_to_one_field",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="example_rel",
                        to="app.forwardonetoone",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReverseManyToMany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "example_fields",
                    models.ManyToManyField(related_name="reverse_many_to_many_rels", to="app.example"),
                ),
                (
                    "forward_many_to_many_fields",
                    models.ManyToManyField(
                        related_name="reverse_many_to_many_rels",
                        to="app.forwardmanytomanyforrelated",
                    ),
                ),
                (
                    "forward_many_to_one_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reverse_many_to_many_rels",
                        to="app.forwardmanytooneforrelated",
                    ),
                ),
                (
                    "forward_one_to_one_field",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reverse_many_to_many_rel",
                        to="app.forwardonetooneforrelated",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReverseManyToManyToForwardManyToMany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "forward_many_to_many_fields",
                    models.ManyToManyField(
                        related_name="reverse_many_to_many_rels",
                        to="app.forwardmanytomany",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReverseManyToManyToForwardManyToOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "forward_many_to_one_fields",
                    models.ManyToManyField(
                        related_name="reverse_many_to_many_rels",
                        to="app.forwardmanytoone",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReverseManyToManyToForwardOneToOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "forward_one_to_one_fields",
                    models.ManyToManyField(
                        related_name="reverse_many_to_many_rels",
                        to="app.forwardonetoone",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReverseManyToManyToReverseManyToMany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "reverse_many_to_many_fields",
                    models.ManyToManyField(
                        related_name="reverse_many_to_many_rels",
                        to="app.reversemanytomany",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReverseOneToMany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "example_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reverse_one_to_many_rels",
                        to="app.example",
                    ),
                ),
                (
                    "forward_many_to_many_fields",
                    models.ManyToManyField(
                        related_name="reverse_one_to_many_rels",
                        to="app.forwardmanytomanyforrelated",
                    ),
                ),
                (
                    "forward_many_to_one_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reverse_one_to_many_rels",
                        to="app.forwardmanytooneforrelated",
                    ),
                ),
                (
                    "forward_one_to_one_field",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reverse_one_to_many_rel",
                        to="app.forwardonetooneforrelated",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReverseManyToManyToReverseOneToMany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "reverse_many_to_one_fields",
                    models.ManyToManyField(
                        related_name="reverse_many_to_many_rels",
                        to="app.reverseonetomany",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReverseOneToManyToForwardManyToMany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "forward_many_to_many_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reverse_one_to_many_rels",
                        to="app.forwardmanytomany",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReverseOneToManyToForwardManyToOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "forward_many_to_one_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reverse_one_to_many_rels",
                        to="app.forwardmanytoone",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReverseOneToManyToForwardOneToOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "forward_one_to_one_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reverse_one_to_many_rels",
                        to="app.forwardonetoone",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReverseOneToManyToReverseManyToMany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "reverse_many_to_many_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reverse_one_to_many_rels",
                        to="app.reversemanytomany",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReverseOneToManyToReverseOneToMany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "reverse_many_to_one_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reverse_one_to_many_rels",
                        to="app.reverseonetomany",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReverseOneToOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "example_field",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reverse_one_to_one_rel",
                        to="app.example",
                    ),
                ),
                (
                    "forward_many_to_many_fields",
                    models.ManyToManyField(
                        related_name="reverse_one_to_one_rels",
                        to="app.forwardmanytomanyforrelated",
                    ),
                ),
                (
                    "forward_many_to_one_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reverse_one_to_one_rels",
                        to="app.forwardmanytooneforrelated",
                    ),
                ),
                (
                    "forward_one_to_one_field",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reverse_one_to_one_rel",
                        to="app.forwardonetooneforrelated",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReverseOneToManyToReverseOneToOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "reverse_one_to_one_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reverse_one_to_many_rels",
                        to="app.reverseonetoone",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReverseManyToManyToReverseOneToOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "reverse_one_to_one_fields",
                    models.ManyToManyField(
                        related_name="reverse_many_to_many_rels",
                        to="app.reverseonetoone",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReverseOneToOneToForwardManyToMany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "forward_many_to_many_field",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reverse_one_to_one_rel",
                        to="app.forwardmanytomany",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReverseOneToOneToForwardManyToOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "forward_many_to_one_field",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reverse_one_to_one_rel",
                        to="app.forwardmanytoone",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReverseOneToOneToForwardOneToOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "forward_one_to_one_field",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reverse_one_to_one_rel",
                        to="app.forwardonetoone",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReverseOneToOneToReverseManyToMany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "reverse_many_to_many_field",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reverse_one_to_one_rel",
                        to="app.reversemanytomany",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReverseOneToOneToReverseOneToMany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "reverse_many_to_one_field",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reverse_one_to_one_rel",
                        to="app.reverseonetomany",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReverseOneToOneToReverseOneToOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "reverse_one_to_one_field",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reverse_one_to_one_rel",
                        to="app.reverseonetoone",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
        ),
    ]
