name: Test

on:
  push:
    branches:
      - main
    paths:
      - "**.py"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/test.yml"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    uses: MrThearMan/CI/.github/workflows/test-nox.yml@v0.6.1
    with:
      uv-cache-suffix: "test"
      coveralls: ${{ fromJSON(vars.COVERALLS_ENABLED || 'false') }}

  test-async:
    uses: MrThearMan/CI/.github/workflows/test-nox.yml@v0.6.1
    with:
      python-version: '["3.14"]'
      os: '["ubuntu-latest"]'
      env: '{"ASYNC": "true"}'
      uv-cache-suffix: 'test-async'
      coveralls: false

  test-mypy:
    name: "Test mypy"
    runs-on: "ubuntu-latest"

    # Cancel old workflows when a new workflow is triggered for the same PR/branch/tag
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash

    steps:
      - name: "Check out repository"
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: "Set up python"
        id: setup-python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"

      - name: "Set up uv"
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.12.10"
          enable-cache: true
          cache-suffix: "mypy"

      - name: "Install dependencies"
        run: |
          uv sync --locked --all-extras --all-groups --python "${{ steps.setup-python.outputs.python-path }}"

      - name: "Run mypy tests"
        run: |
          uv run --no-sync python manage.py generate_test_mypy_yml
          RUN_MYPY_TESTS=1 uv run --no-sync pytest tests/test_mypy/cases/*.yml
