name: Test

on:
  push:
    branches:
      - main
    paths:
      - "**.py"
      - "pyproject.toml"
      - "poetry.lock"
      - ".github/workflows/test.yml"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    uses: MrThearMan/CI/.github/workflows/test-nox.yml@v0.5.1
    with:
      python-version: '["3.11", "3.12", "3.13", "3.14"]'

  test-async:
    uses: MrThearMan/CI/.github/workflows/test-nox.yml@v0.5.1
    with:
      python-version: '["3.11", "3.12", "3.13", "3.14"]'
      env: '{"ASYNC": "true"}'
      coveralls: false
